### ISSUE TITLE
no transcription and translation

### ISSUE THREAD

**Issue by zxcvbn2949** [glutanimate/pdf-glossary#4] opened 2018-04-08 18:24 UTC
http://prntscr.com/j2kl07

**Comment by glutanimate** [comment] 2018-04-08 18:26
Duplicate of #3.

**Closed as completed by glutanimate** 2018-04-08 18:26 UTC

**Comment by zxcvbn2949** [comment] 2018-04-08 19:39
so what should I do to make it work?08.04.2018, 21:26, "Aristotelis" <notifications@github.com>:Closed #4.
